-- MySQL Script generated by MySQL Workbench
-- 08/26/18 10:41:12
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema myblog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema myblog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `myblog` DEFAULT CHARACTER SET utf8 COLLATE utf8_latvian_ci ;
USE `myblog` ;

-- -----------------------------------------------------
-- Table `myblog`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myblog`.`admin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(32) NOT NULL COMMENT 'base64 encrypt',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myblog`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myblog`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_time` DATETIME NOT NULL,
  `updated_time` DATETIME NOT NULL,
  `parent_id` INT NULL COMMENT 'parent category',
  `name` VARCHAR(45) NOT NULL,
  `status` VARCHAR(1) NOT NULL DEFAULT '1',
  `remark` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myblog`.`blog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myblog`.`blog` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_time` DATETIME NOT NULL,
  `updated_time` DATETIME NOT NULL,
  `blog_num` VARCHAR(8) NOT NULL COMMENT 'blog num, uuid, article html addr.',
  `category_id` INT NOT NULL,
  `author` INT NOT NULL COMMENT 'admin id',
  `remark` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_blog_category_pk_idx` (`category_id` ASC),
  CONSTRAINT `fk_blog_category_pk`
    FOREIGN KEY (`category_id`)
    REFERENCES `myblog`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myblog`.`read_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myblog`.`read_record` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_time` DATETIME NOT NULL,
  `updated_time` DATETIME NOT NULL,
  `blog_id` INT NOT NULL,
  `client_ip` VARCHAR(15) NOT NULL,
  `remark` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_read_record_blog_pk_idx` (`blog_id` ASC),
  CONSTRAINT `fk_read_record_blog_pk`
    FOREIGN KEY (`blog_id`)
    REFERENCES `myblog`.`blog` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myblog`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myblog`.`comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_time` DATETIME NOT NULL,
  `blog_id` INT NULL COMMENT 'if blog id is not null, the comment is for this blog. else, the comment is for website',
  `parent_id` INT NOT NULL,
  `client_ip` VARCHAR(15) NOT NULL,
  `client_name` VARCHAR(45) NOT NULL,
  `client_email` VARCHAR(45) NOT NULL,
  `content` VARCHAR(255) NOT NULL,
  `remark` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comments_blog_id_idx` (`blog_id` ASC),
  CONSTRAINT `fk_comments_blog_id`
    FOREIGN KEY (`blog_id`)
    REFERENCES `myblog`.`blog` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
